### ISSUE TITLE
Saraiki language

### ISSUE THREAD

**Issue by mpQadir** [google-research-datasets/uninum#19]
In this site Saraiki is put at two places. It should be made one. There are mistakes in Saraiki numbers also. These entries be corrected please.
ہک
ݙو
ترائے
چار
پنج
چھی
ست
اٹھ 
نو
ݙاہ
یارھاں
ٻارھاں
تیرھاں
چوݙاں
پندرھاں
سولھاں
ستارھاں
اٹھارھاں
اُنویہ
ویہ
اکویہ
ٻاویہ
تریویہ
چویہ
پنجویہ
چھویہ
ستاویہ
اٹھاویہ
اُنتریہ
تریہ
اکتریہ
ٻتریہ
تیتریہ
چونتری
پینتریہ
چھتریہ
ستتریہ
اٹھتریہ
انتالیہ
چالیہ
اکتالیہ
ٻتالیہ
ترتالیہ
چُتالیہ
پینتالیہ
چھتالیہ
سینتالیہ
اڑتالیہ
اُنجھاہ
پنجھاہ
اکونجھا
ٻونجھا
ترونجھا
چُرونجھا
پچونجھا
چھونجھا
ستونجھا
اٹھونجھا
اُنیٹھ
سٹھ
اکیٹھ
ٻیٹھ
تریٹھ
چویٹھ
پنجیٹھ
چھیٹھ
ستیٹھ
اٹھیٹھ
انہتر
ستر
اکہتر
ٻہتر
تہتر
چوہتر
پنجہتر
چھہتر
ستتر
اٹھہتر
اناسی
اسی
اکاسی
ٻیاسی
تراسی
چوراسی
پنجاسی
چھیاسی
ستاسی
اٹھاسی
انانوے
نوے
اکانوے
ٻیانوے
تریانوے
چورانوے
پنجانوے
چھیانوے
ستانوے
اٹھانوے
ودھانوے
سو
ہک ہزار 
ݙاہ ہزار
ہک لکھ
ݙاہ لکھ
 ہک کروڑ
ݙاہ کروڑ
ہک ارب
ݙاہ ارب
ہک کھرب 
ݙاہ کھرب

**Comment by kylebgorman** [comment]
Please sign the CLA and file a pull request.

**Comment by mpQadir** [comment]
I don't know about the process. Kindly this be done by expert.

**Comment by kylebgorman** [comment]
The only way we can fix this is if a native speaker (like yourself, if you speak this language) volunteers to submit a pull request and signs the CLA. Otherwise I have to close this issue; we don't have a way to quickly find a native speaker with the expertise to do this, and this database is only put forth as a gift to the community in case it is useful. However, you're welcome to research how to file a pull request---it's not hard.

**Comment by mpQadir** [comment]
Thanks. Very much. Saraiki be one language in codes.tsv
